apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761         # Service端口（集群内部访问）
      targetPort: 8761   # 容器暴露端口
      nodePort: 30061    # 本机访问端口（NodePort）
  type: NodePort
